Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: dev
    awsaccountid:
        Description: AWS Account ID
        Type: String
    aggregatorregion:
        Description: Regon where config aggregator resides
        Type: String
Resources:        
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties: 
      Name:
        Fn::Join:
        - ""
        - - 'config'
          - !Ref Stack
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: false
      RoleARN:
        Fn::Join:
        - ""
        - - 'arn:aws:iam::'
          - !Ref awsaccountid
          - ':role/config-role-'
          - !Ref Stack
  
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name:
        Fn::Join:
        - ""
        - - 'config-delivery-channel'
          - !Ref Stack
      S3BucketName:
        Fn::Join:
        - ""
        - - 'config-bucket-'
          - !Ref Stack
          - '-'
          - !Ref awsaccountid
  
  AggregatorAuthorization:
    Type: AWS::Config::AggregationAuthorization
    Properties: 
      AuthorizedAccountId: !Ref awsaccountid
      AuthorizedAwsRegion: !Ref aggregatorregion







